import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/header';
import localFont from 'next/font/local';
import { Poppins, Noto_Sans_Arabic } from 'next/font/google';

const ar_font = Noto_Sans_Arabic({
  subsets: ['arabic'],
  weight: '400',
});

export const metadata: Metadata = {
  title: 'E-SAUDI STORE',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' dir='rtl'>
      <body className={ar_font.className + ' max-w-7xl mx-auto'}>
        <Header />
        {children}
      </body>
    </html>
  );
}
